### ISSUE TITLE
Remove sync version?

### ISSUE THREAD

**Issue by lukeed** [terkelg/eliminate#2]
This looks almost exactly like one of my internal tools 😆 

I would _maybe_ suggest that since you're shipping code with `async` syntax, that there's no/little point in shipping a sync version of the code.

This is because having `async` (and `fs.rmdir`) in the code _at all_, even when not imported, forces a Node 7.6+ environment, wherein native `async` is available. 

So, anyone using this lib can/should have an `async` parent function that `await`s this guy. You'd only be dropping support for top-level usage, which is easily fixed anyway.

**Comment by terkelg** [comment]
Agree fd44c02032ee303f6e24ad3665c5590a935a869f removes the sync version. 👍

**Comment by lukeed** [comment]
Nice~! 🎉
